### ISSUE TITLE
Extension not listed in R# 2022.1.0

### ISSUE THREAD

**Issue by ElStefan** [hhu-mahmoud/ExceptionalReSharper#11]
Hi, I just checked if all my extensions were updated and installed ReSharper 2022.1.0. 

I saw the commit c1c1c271 from end of March, expecting this extension to be available, but it is not in the list.
[JetBrains Marketplace](https://plugins.jetbrains.com/plugin/14928-exceptional-by-mf/versions) still shows this new version of the extension only to be compatible with 2021.3

**Comment by HelenAvelin** [comment]
I am having the same problem.

**Comment by Christian-GB-DE** [comment]
Also a Problem for me. Can't see the Extension in the Extension-Manager - also when manual download an setup an local Path for the Extensions.

**Comment by hhu-mahmoud** [comment]
@ElStefan @ElStefan  @Christian-GB-DE  @RobertWeinmeister 

Sorry for to late update. I have updated the extension now and it will be within 24 Hours Online Version 2022.2.0

**Comment by hhu-mahmoud** [comment]
Extension is now Online.
