### ISSUE TITLE
Question: Is this extension working only for public methods? 

### ISSUE THREAD

**Issue by seerek** [hhu-mahmoud/ExceptionalReSharper#9]
I'm using this extension for the first time.
Love the idea, but noticed strange behaviour - seems that this extension analyzes method code only when it is public. The moment I change method signature to private, it doesn't work.

1. Is it by design?
2. Can I somehow configure it (and enable for all methods)?

Thanks

**Comment by hhu-mahmoud** [comment]
@seerek sorry for too late answer. of course you can use this extension in the private methods also.
in VS => Extensions => Resharper => Options => Exceptional => Inspection Level => "Inspect private methods" => Save

![grafik](https://user-images.githubusercontent.com/32834850/161042202-dc6c43e2-861d-4d16-9c68-3553108f9c90.png)

**Comment by seerek** [comment]
Thank you.
Works like a charm.

I've completely missed options for this extension.
